# Staging Environment Configuration
server:
  port: 8080
  tls_port: 8443
  host: "0.0.0.0"
  read_timeout: 60
  write_timeout: 60

tls:
  cert_file: "certs/cert.pem"
  key_file: "certs/key.pem"
  min_version: "1.2"

authentication:
  api_key: "${API_KEY}"  # Use environment variable
  enable_auth: true

logging:
  level: "info"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  port: 9090
  path: "/metrics"

connection_pool:
  max_connections: 500
  max_idle_connections: 50
  idle_timeout: 600

load_balancer:
  targets:
    - "bore-server-1:8080"
    - "bore-server-2:8080"
  algorithm: "round_robin"

monitoring:
  health_check_interval: 30
  enable_prometheus: true

database:
  host: "${DB_HOST}"
  port: 5432
  name: "bore_staging"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"