name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

    - name: Run go vet
      run: go vet ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m

    - name: Check commit messages
      if: github.event_name == 'pull_request'
      run: |
        # Check if PR title follows conventional commit format
        PR_TITLE="${{ github.event.pull_request.title }}"
        if ! echo "$PR_TITLE" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(\(.+\))?: "; then
          echo "❌ PR title does not follow conventional commit format"
          echo "Expected format: type(scope): description"
          echo "Example: feat: add new tunneling feature"
          exit 1
        fi
        echo "✅ PR title follows conventional commit format"

    - name: Create bin directory
      run: mkdir -p bin

    - name: Build server
      run: go build -o bin/server ./cmd/server

    - name: Build client
      run: go build -o bin/client ./cmd/client

    - name: Verify builds
      run: |
        ls -la bin/
        file bin/server
        file bin/client

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker build --target server -t bore-server:latest .
        docker build --target client -t bore-client:latest .

    - name: Test Docker images
      run: |
        docker run --rm bore-server:latest --help || true
        docker run --rm bore-client:latest --help || true
